### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by linhnd99** [vikage/MVVM-C#1]
https://github.com/vikage/MVVM-C/blob/7ca63359ea7d67b2c8eb82dc07ef3d4b4aa52a6a/MVVM-C.xctemplate/___FILEBASENAME___ViewController.swift#L7

**Comment by vikage** [comment]
@linhnd99 Please create a PR

**Comment by linhndSolar** [comment]
I can't push code because of no permission

**Comment by vikage** [comment]
@linhnd99 🐓 🤣
